version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:4173" # HostPort:ContainerPort
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src  # Mount the source code directory
      - ./vite.config.ts:/usr/src/app/vite.config.ts # Mount configuration file
